version: '3'

services:
  backend:
    # Aquí Docker descargará tu imagen desde la nube automáticamente
    image: cesarric/pinguino-backend:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - pinguino-net

  nginx:
    # Aquí descargará el juego completo (HTML/JS/CSS ya están dentro)
    image: cesarric/pinguino-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pinguino-net

networks:
  pinguino-net:
    driver: bridge
